theme: jekyll-theme-cayman

title: [Hi! I'm Tanvi Roy]
description: [Predictably unpredictable.]

<!DOCTYPE html>
<html>
	<head>
		<title>Hank Quinlan, Horrible Cop</title>
		<!-- link to main stylesheet -->
		<link rel="stylesheet" type="text/css" href="/css/main.css">
	</head>
	<body>
		<nav>
    		<ul>
        		<li><a href="/">Home</a></li>
	        	<li><a href="/about">About</a></li>
        		<li><a href="/cv">CV</a></li>
    		</ul>
		</nav>
		<div class="container">
    		<div class="blurb">
        		<h1>Hi! I'm Tanvi Roy</h1>
				<p>I'm a 19 year old freshman at Ashoka University, India.</p>
    		</div><!-- /.blurb -->
		</div><!-- /.container -->
		<footer>
    		<ul>
        		<li><a href="mailto:tanvi.roy_ug22@ashoka.edu.in">email</a></li>
        		<li><a href="https://github.com/tnvichan">github.com/tnvichan</a></li>
			</ul>
		</footer>
	</body>
</html>
